#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Configuration du catalogue ARCenal..."
arcenal_exiger_url_catalogue
arcenal_verifier_catalogue

if test -f /etc/yunohost/apps_catalog.yml; then
    cp --preserve=mode,timestamps /etc/yunohost/apps_catalog.yml "$YNH_APP_SETTING_PATH/catalogue-pre-arcenal.yml"
else
    touch "$YNH_APP_SETTING_PATH/catalogue-pre-arcenal.absent"
fi

arcenal_ecrire_catalogue
ynh_app_setting_set --key=catalogue_url --value="$catalogue_url"
arcenal_actualiser_catalogue
ynh_script_progression "Catalogue ARCenal stable activé."
