#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Configuration de l'espace personnel ARCenal..."
arcenal_exiger_store
arcenal_initialiser_identite
arcenal_deployer_espace
ynh_script_progression "Espace personnel ARCenal activé."
