#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Mise à jour de la configuration ARCenal..."
arcenal_exiger_url_catalogue
arcenal_verifier_catalogue
arcenal_ecrire_catalogue
ynh_app_setting_set --key=catalogue_url --value="$catalogue_url"
arcenal_actualiser_catalogue
domaine="$(ynh_app_setting_get --key=domaine_portail)"
domaine="${domaine:-$(ynh_get_main_domain)}"
ynh_script_progression "Mise à jour du portail ARCenal..."
arcenal_activer_portail "$domaine"
ynh_app_setting_set --key=domaine_portail --value="$domaine"
ynh_script_progression "Configuration ARCenal mise à jour."
